#!/bin/sh

wifi_stat=$(cat /sys/class/net/w*/operstate 2>/dev/null)
eth_stat=$(cat /sys/class/net/e*/operstate 2>/dev/null)
vpn_stat=$(cat /sys/class/net/tun*/operstate 2>/dev/null)

if [ "$vpn_stat" == "up" ]; then
	echo -n "🔒"
fi

if [ "$wifi_stat" == "up" ]; then
	# echo " $(nmcli -g active,ssid dev wifi | /usr/bin/grep 'yes' | cut -f 2 -d ':')"
	echo ""
elif [ "$eth_stat" == "up" ]; then
	echo "🌐"
else
	echo ""
fi
