#!/bin/sh

[ $(pacmd list-sinks | awk '/muted/ { print $2 }') = "yes" ] && echo  && exit

vol="$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')"

if [ "$vol" -gt "70" ]; then
	icon=" "
elif [ "$vol" -lt "30" ]; then
	icon=" "
else
	icon=" "
fi

echo " $icon$vol%"
